apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 28080
      targetPort: 80
      protocol: TCP
      nodePort: 28080
    - name: https
      port: 28443
      targetPort: 443
      protocol: TCP
      nodePort: 28443
    # - name: proxied-udp-53
    #   port: 53
    #   targetPort: 53
    #   protocol: UDP
    #   nodePort: 53
    # - name: proxied-tcp-53
    #   port: 53
    #   targetPort: 53
    #   protocol: TCP
    #   nodePort: 53
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
