# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-travis?view=azure-devops

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - 7.*

jobs:
- job: build
  strategy:
    maxParallel: 1
    matrix:
      # PHP_73_CLI:
      #   PHP_VERSION: 7_3_X
      #   FOLDER: 7.3
      #   PHP_TAG_VERSION: 7.3.17
      #   CLI: 1
      # PHP_73_FPM:
      #   PHP_VERSION: 7_3_X
      #   FOLDER: 7.3
      #   PHP_TAG_VERSION: 7.3.17
      #   FPM: 1
      # PHP_73_COMPOSER:
      #   PHP_VERSION: 7_3_X
      #   FOLDER: 7.3
      #   PHP_TAG_VERSION: 7.3.17
      #   COMPOSER: 1
      # PHP_73_SWOOLE:
      #   PHP_VERSION: 7_3_X
      #   FOLDER: 7.3
      #   PHP_TAG_VERSION: 7.3.17
      #   SWOOLE: 1
      # PHP_73_UNIT:
      #   PHP_VERSION: 7_3_X
      #   FOLDER: 7.3
      #   PHP_TAG_VERSION: 7.3.17
      #   UNIT: 1
      # PHP_73_SUPERVISORD:
      #   PHP_VERSION: 7_3_X
      #   FOLDER: 7.3
      #   PHP_TAG_VERSION: 7.3.17
      #   SUPERVISORD: 1
      # PHP_73_PPM:
      #   PHP_VERSION: 7_3_X
      #   FOLDER: 7.3
      #   PHP_TAG_VERSION: 7.3.17
      #   PPM: 1

      # PHP_56_FPM:
      #   PHP_VERSION: 5_6_X
      #   FOLDER: 5.6
      #   PHP_TAG_VERSION: 5.6.40
      #   FPM: 1

      # PHP_70_FPM:
      #   PHP_VERSION: 7_0_X
      #   FOLDER: 7.0
      #   PHP_TAG_VERSION: 7.0.33
      #   FPM: 1

      # PHP_71_FPM:
      #   PHP_VERSION: 7_1_X
      #   FOLDER: 7.1
      #   PHP_TAG_VERSION: 7.1.33
      #   FPM: 1

      PHP_72_CLI:
        PHP_VERSION: 7_2_X
        FOLDER: 7.2
        PHP_TAG_VERSION: 7.2.30
        CLI: 1
      PHP_72_FPM:
        PHP_VERSION: 7_2_X
        FOLDER: 7.2
        PHP_TAG_VERSION: 7.2.30
        FPM: 1
      PHP_72_COMPOSER:
        PHP_VERSION: 7_2_X
        FOLDER: 7.2
        PHP_TAG_VERSION: 7.2.30
        COMPOSER: 1
      PHP_72_SWOOLE:
        PHP_VERSION: 7_2_X
        FOLDER: 7.2
        PHP_TAG_VERSION: 7.2.30
        SWOOLE: 1
      PHP_72_UNIT:
        PHP_VERSION: 7_2_X
        FOLDER: 7.2
        PHP_TAG_VERSION: 7.2.30
        UNIT: 1
      PHP_72_SUPERVISORD:
        PHP_VERSION: 7_2_X
        FOLDER: 7.2
        PHP_TAG_VERSION: 7.2.30
        SUPERVISORD: 1
      PHP_72_PPM:
        PHP_VERSION: 7_2_X
        FOLDER: 7.2
        PHP_TAG_VERSION: 7.2.30
        PPM: 1

      # PHP_74_CLI:
      #   PHP_VERSION: 7_4_X
      #   FOLDER: 7.4
      #   PHP_TAG_VERSION: 7.4.5
      #   CLI: 1
      # PHP_74_FPM:
      #   PHP_VERSION: 7_4_X
      #   FOLDER: 7.4
      #   PHP_TAG_VERSION: 7.4.5
      #   FPM: 1
      # PHP_74_COMPOSER:
      #   PHP_VERSION: 7_4_X
      #   FOLDER: 7.4
      #   PHP_TAG_VERSION: 7.4.5
      #   COMPOSER: 1
      # PHP_74_SWOOLE:
      #   PHP_VERSION: 7_4_X
      #   FOLDER: 7.4
      #   PHP_TAG_VERSION: 7.4.5
      #   SWOOLE: 1

      # PHP_nightly_CLI:
      #   PHP_VERSION: nightly
      #   FOLDER: nightly
      #   PHP_TAG_VERSION: nightly
      #   CLI: 1
      # PHP_nightly_FPM:
      #   PHP_VERSION: nightly
      #   FOLDER: nightly
      #   PHP_TAG_VERSION: nightly
      #   FPM: 1
      # PHP_nightly_COMPOSER:
      #   PHP_VERSION: nightly
      #   FOLDER: nightly
      #   PHP_TAG_VERSION: nightly
      #   COMPOSER: 1
      # PHP_nightly_SWOOLE:
      #   PHP_VERSION: nightly
      #   FOLDER: nightly
      #   PHP_TAG_VERSION: nightly
      #   SWOOLE: 1

  pool:
    vmImage: 'ubuntu-latest'

  variables:
  - group: docker
  - name: DOCKER_CLI_EXPERIMENTAL
    value: enabled
  - name: DOCKER_COMPOSE_VERSION
    value: 1.25.0
  timeoutInMinutes: 0
  steps:
  - script: |
      set -x
      env
      docker --version
      docker-compose --version
    displayName: 'manifest'
  - script: |
      set -x
      export DOCKER_CHANNEL=test
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) ${DOCKER_CHANNEL}"
      sudo apt-get update
      sudo apt-get -y install docker-ce
      sudo rm /usr/local/bin/docker-compose
      curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      chmod +x docker-compose
      sudo mv docker-compose /usr/local/bin
      sudo mkdir -p /etc/systemd/system/docker.service.d
      echo -e '[Service]\nExecStart=\nExecStart=/usr/bin/dockerd' | sudo tee /etc/systemd/system/docker.service.d/docker.conf
      echo '{"hosts":["unix:///var/run/docker.sock","tcp://0.0.0.0:2375"],"experimental":true}' | sudo tee /etc/docker/daemon.json
      sudo systemctl daemon-reload
      sudo systemctl cat docker
      sudo systemctl restart docker
      sleep 5
      docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      cat /proc/sys/fs/binfmt_misc/qemu-aarch64
      docker buildx create --name mybuilder
      docker buildx use mybuilder
      docker buildx inspect --bootstrap
    displayName: 'Setup Docker'
  - script: |
      set -x
      docker --version
      docker-compose --version
      docker buildx version
      docker
    displayName: 'install-after-manifest'
  - script: |
      set -x
      echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
      echo $(DOCKER_PASSWORD) | docker login -u $(TENCENT_DOCKER_USERNAME) --password-stdin uswccr.ccs.tencentyun.com
      echo #echo $(DOCKER_PASSWORD) | docker login -u $(ALIYUN_DOCKER_USERNAME) --password-stdin registry.us-west-1.aliyuncs.com
    displayName: 'Docker Login'

  - script: |
      cp .env.example .env
      set -ex

      if [ ! `echo $BUILD_SOURCEBRANCH | grep 'refs/tags/'` ];then \
        export PLATFORM=linux/amd64; \
        if [ "$PHP_VERSION" = 8_0_X -o "$PHP_VERSION" = nightly ];then \
          export PLATFORM=linux/amd64,linux/arm64,linux/arm/v7; \
          IS_PUSH=--push; \
          mirror="${add_mirror}"; \
        else \
          IS_PUSH=--push; \
          DOCKER_HUB_USERNAME=lrew; \
        fi; \
      else \
          IS_PUSH=--push \
          && mirror="${add_mirror}"; \
      fi

      VCS_REF=`git rev-parse --short HEAD`
      options="--build-arg VCS_REF=$VCS_REF"
      echo $options

      if [ -n "$UNIT" ];then docker buildx build $options \
        --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
        -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-unit-alpine \
        $(for item in `echo $mirror`;do echo " -t ${item}:${PHP_TAG_VERSION}-unit-alpine ";done) \
        --platform ${PLATFORM} \
        ${IS_PUSH} ${FOLDER}/unit; \
      fi

      if [ -n "$SUPERVISORD" ];then docker buildx build $options \
        --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
        -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-supervisord-alpine \
        $(for item in `echo $mirror`;do echo " -t ${item}:${PHP_TAG_VERSION}-supervisord-alpine ";done) \
        --platform ${PLATFORM} ${IS_PUSH} ${FOLDER}/supervisord; \
      fi

      if [ -n "$COMPOSER" ];then docker buildx build $options \
        --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
        -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-composer-alpine \
        $(for item in `echo $mirror`;do echo " -t ${item}:${PHP_TAG_VERSION}-composer-alpine ";done) \
        --platform ${PLATFORM} ${IS_PUSH} ${FOLDER}/composer; \
      fi

      if [ -n "$SINGLE" ];then docker buildx build $options \
        --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
        -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-single-alpine \
        ${IS_PUSH} ${FOLDER}/single; \
      fi

      if [ -n "$SWOOLE" ];then docker buildx build $options \
        --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
        -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-swoole-alpine \
        $(for item in `echo $mirror`;do echo " -t ${item}:${PHP_TAG_VERSION}-swoole-alpine ";done) \
        --platform ${PLATFORM} ${IS_PUSH} ${FOLDER}/swoole; \
      fi

      if [ -n "$FPM" ];then docker buildx build $options \
        --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
        --target=php -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-fpm-alpine \
        $(for item in `echo $mirror`;do echo " -t ${item}:${PHP_TAG_VERSION}-fpm-alpine ";done) \
        ${fpmTagOptions} \
        --platform ${PLATFORM} \
        ${IS_PUSH} ${FOLDER}/alpine; \
      fi

      if [ -n "$CLI" ];then docker buildx build $options \
        --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
        -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-cli-alpine \
        $(for item in `echo $mirror`;do echo " -t ${item}:${PHP_TAG_VERSION}-cli-alpine ";done) \
        --platform ${PLATFORM} \
        ${IS_PUSH} ${FOLDER}/cli; \
      fi

      if [ -n "$PPM" ];then docker buildx build $options \
        --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
        -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-ppm-alpine \
        $(for item in `echo $mirror`;do echo " -t ${item}:${PHP_TAG_VERSION}-ppm-alpine ";done) \
        --platform ${PLATFORM} \
        ${IS_PUSH} ${FOLDER}/ppm; \
      fi
    env:
      DOCKER_HUB_USERNAME: khs1994
      PLATFORM: linux/amd64,linux/arm64,linux/arm/v7
      # add_mirror: uswccr.ccs.tencentyun.com/khs1994/php registry.us-west-1.aliyuncs.com/khs1994/php
    displayName: 'Build Image'
    timeoutInMinutes: 0

  - script: |
      curl -X POST https://hooks.microbadger.com/images/$DOCKER_HUB_USERNAME/php/OMVCEKSr9I0cjhU0DQop3HwjYAc=
    displayName: 'Trigger hooks'
    env:
      DOCKER_HUB_USERNAME: khs1994
    condition: succeeded()
